### ISSUE TITLE
Blacklist only works with comma separated lists

### ISSUE THREAD

**Issue by KevinJRussell** [KevinJRussell/Carbonation#1]
The blacklist should be made to work with both comma separated lists and comma-space separated lists for ease of use.

I originally tried to split on comma and check each element for trailing spaces, then trim the space, but it didn't work. My initial suspicion is that the .foreach loop does not allow you to change the individual elements in that manner.

**Comment by ScottDikowitz** [comment]
I think you want .map? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by KevinJRussell** [comment]
Oh, yeah, I think that would work. I think the real problem is that you just can't overwrite the values in the existing array for some reason. Fuck Javascript. Thanks

**Comment by ScottDikowitz** [comment]
Yeah, forEach passes by value. But within the forEach you could modify the array like blacklist[index] = ...
